<a href="https://colab.research.google.com/github/namannarula/tensorflow-colab-notebooks/blob/main/FashonMNIST_ComputerVision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Importing Libraries**

In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

# **Setting up callback**

In [15]:
class myCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs={}):
    if(logs.get('loss')<0.4):
      print("\nReached 60% accuracy so cancelling training!")
      self.model.stop_training = True

callbacks = myCallback()

# **Loading the Dataset**

In [16]:
mnist = tf.keras.datasets.fashion_mnist

In [17]:
(training_images, training_labels), (test_images, test_labels) = mnist.load_data()

In [18]:
np.set_printoptions(linewidth=200)
print(training_labels[0])
print(training_images[0])

9
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   1   0   0  13  73   0   0   1   4   0   0   0   0   1   1   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3   0  36 136 127  62  54   0   0   0   1   3   4   0   0   3]
 [  0   0   0   0   0   0   0   0   0   0   0   0   6   0 102 204 176 134 144 123  23   0   0   0   0  12  10   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0 155 236 207 178 107 156 161 109  64  23  77 130  72  15]
 [  0   0   0   0   0   0   0   0   0   0   0   1   0  69 207 223 218 216 216 163 127 121 122 146 141  88 172  66]
 [  0   0   0   0   0   0   0   0   0   1   1   1   0 200 232 232 233 229 223 

# **Normalizing the Data**

In [19]:
training_images  = training_images / 255.0
test_images = test_images / 255.0

# **Designing the Model**

In [20]:
model = tf.keras.models.Sequential([tf.keras.layers.Flatten(), 
                                    tf.keras.layers.Dense(128, activation=tf.nn.relu), 
                                    tf.keras.layers.Dense(10, activation=tf.nn.softmax)])

# **Compiling the Model**

In [21]:
model.compile(optimizer = tf.optimizers.Adam(),
              loss = 'sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(training_images, training_labels, epochs=35, callbacks=[callbacks])

Epoch 1/35
1875/1875 [==============================] - 4s 2ms/step - loss: 0.6146 - accuracy: 0.7879
Epoch 2/35
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3836 - accuracy: 0.8635

Reached 60% accuracy so cancelling training!


# **Evalutating the trained model**

In [22]:
model.evaluate(test_images, test_labels)

313/313 [==============================] - 1s 1ms/step - loss: 0.4027 - accuracy: 0.8532


[0.4026719629764557, 0.8532000184059143]

## **Predicting with the model**

In [23]:
classifications = model.predict(test_images)

print(classifications[0])
print(test_labels[0])

[1.3910467e-04 2.3859711e-06 3.0135581e-05 4.4176309e-06 5.0096736e-05 4.1741773e-02 1.0927075e-04 5.5136092e-02 4.8289662e-03 8.9795774e-01]
9
